---
dependency:
  name: galaxy
driver:
  name: epc
lint:
  name: yamllint
  options:
    config-file: molecule/yamllint.yml
platforms:
  - name: test-node-hybris-prepare
    shape: LARGE
    wait_timeout: 1800
    image: CentOS7_64-bit
    groups:
      - dev
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: playbook.yml
scenario:
  name: cloud-aws
verifier:
  name: testinfra
  lint:
    name: flake8
