---

stages:
  - lint
  - deployment test

before_script:
  # Check ansible version
  - ansible --version
  - molecule --version
  - docker --version
  - rm -rf ~/ansible-lint-rules
  - git clone -b 1.0.1 https://github.com/lean-delivery/ansible-lint-rules.git ~/ansible-lint-rules

after_script:
  - rm -rf ~/ansible-lint-rules

Check lint:
  stage: lint
  script:
    - ansible-lint -c .ansible-lint `find . -regex ".*\.\(yml\)"`
  tags:
    - molecule2.4

Docker node-hybris-prepare:
  stage: deployment test
  script:
    - wget https://touch.epm-esp.projects.epam.com/static-files/centos7.dockerfile.j2 -O molecule/default/Dockerfile.j2
    - molecule test -s default  --destroy=always
  tags:
    - molecule2.4

EPC node-hybris-prepare:
  variables:
    MOLECULE_INCLUDE_ANSIBLE_CFG: "true"
    EPC_REGION: EPAM-BY2
  stage: deployment test
  script:
    - molecule test -s cloud-epc  --destroy=always
  tags:
    - molecule2.4

AWS node-hybris-prepare:
  variables:
    MOLECULE_INCLUDE_ANSIBLE_CFG: "true"
    EPC_REGION: AWS-EUCENTRAL
  stage: deployment test
  script:
    - molecule test -s cloud-aws --destroy=always
  tags:
    - molecule2.4
