---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/yamllint.yml
platforms:
  - name: node-hybris-prepare-cetos7
    groups:
      - hybris_ct
    image: centos:7
    privileged: True
# - name: node-hybris-prepare-ubuntu1604
#   groups:
#     - hybris_ct
#   image: ubuntu:xenial
#   privileged: True
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
